// 1 - CRIAR USUARIO - OK

####
POST http://localhost:3306/user/signup
Content-Type: application/json

{
    "email": "teste@labenu.com",
    "password": "111111",
    "name": "Teste",
    "role":"ADMIN"
}


// 2 - LOGIN

####
GET http://localhost:3306/user/login
Content-Type: application/json

{
    "email": "teste@labenu.com",
    "password": "111111"
    
}


// 3 - CRIAR BANDA

####
POST http://localhost:3306/band/create
Content-Type: application/json
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc2NzI4MGMwLWY2OTUtNDBiMS1hMDM1LWVhMTQ0OWZkYmFjZiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3ODg0NjY3NSwiZXhwIjoxNjc4ODQ4NDc1fQ.bMmciEsLyjkPHz-RvrAqcnRtZvCG2P5IN6e1IUkkNpU"

{
    "name": "AC DC",
    "music_genre": "Hard Rock",
    "responsible": "Angus"
    
}

